.DEFAULT_GOAL := help

SYMFONY = symfony
SF_CONSOLE = $(SYMFONY) console
YARN = yarn
COMPOSER = $(SYMFONY_BIN) composer
PHPUNIT = $(SYMFONY_BIN) php bin/phpunit

## Help
.PHONY: help
help: ## Get command list
	@grep -E '(^[a-zA-Z_-]+:.*?##.*$$)|(^##)' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[32m%-30s\033[0m %s\n", $$1, $$2}' | sed -e 's/\[32m##/[33m/'


## —— Symfony 🎵 ———————————————————————————————————————————————————————————————

.PHONY: run
run: ## Start local server
	@$(SYMFONY) serve

.PHONY: install assets
vendor: ## Install composer
	@$(COMPOSER) install

node_modules: yarn.lock ## Install node packages
	@$(YARN) install

assets: node_modules ## Run Webpack Encore to compile development assets
	@$(YARN) dev

install: vendor node_modules ## Install project
	make assets

sf: ## List all Symfony commands
	$(SYMFONY)

cc: ## Clear the cache.
	$(SF_CONSOLE) c:c

purgevarlog: ## Purge cache and logs
	@rm -rf var/*
	@echo "var/ purged"

purgeassets: ## Purge node_modules and vendor
	@rm -rf node_modules/ vendor/
	@echo "Assets purged"

purgebuild: ## Purge public/build/ generated by webpack
	@rm -rf public/build/
	@echo "Build Assets purged"

purgeall: purgevarlog purgeassets purgebuild ## Purge Var/ node_modules/ vendor/ public/build/ files
	@echo "Assets purged"

db: ## Build the DB, control the schema validity and check the migration status
	$(SF_CONSOLE) doctrine:cache:clear-metadata
	$(SF_CONSOLE) doctrine:database:create --if-not-exists
	$(SF_CONSOLE) doctrine:schema:drop --force
	$(SF_CONSOLE) doctrine:schema:create
	$(SF_CONSOLE) doctrine:schema:validate

fixtures: db ## Load default fixtures
	$(SF_CONSOLE) doctrine:fixtures:load --no-interaction
